name: Compile on Ubuntu

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - '**/README.md'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  OPENMPI_VER: 5.0.3
  BUILD_TYPE: Release
  NDIM: 3

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Cache dependencies
      id: cache-dependencies
      uses: actions/cache@v4
      with:
        path: /home/runner/.openmpi
        key: ${{runner.os}}-openmpi-${{env.OPENMPI_VER}}
  
    - name: Install dependencies
      if: steps.cache-dependencies.outputs.cache-hit != 'true'
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get install g++-13
        sudo apt install gcc-13
        wget https://download.open-mpi.org/release/open-mpi/v5.0/openmpi-${{env.OPENMPI_VER}}.tar.gz
        gunzip -c openmpi-${{env.OPENMPI_VER}}.tar.gz | tar xf -
        cd openmpi-${{env.OPENMPI_VER}}
        ./configure --prefix="/home/${USER}/.openmpi"
        sudo make all install

    - name: Configure OpenMPI 
      # Set environment variables related to OpenMPI
      run: |
        export PATH=${PATH}:/home/${USER}/.openmpi/bin/
        export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/home/${USER}/.openmpi/lib/
        export OPAL_PREFIX=/home/${USER}/.openmpi

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DNDIM=${{env.NDIM}} -DCMAKE_CXX_COMPILER=g++-13 -DCMAKE_C_COMPILER=gcc-13 -DMPI_HOME=/home/${USER}/.openmpi

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
